name: Fly Deploy
on:
  push:
    branches:
      - main

env:
  APP_NAME: white-haze-2969

jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - uses: actions/setup-go@v3
          with:
            go-version: 1.19
        
        - name: Go Build
          run: go build -v ./...

        - name: Go Test
          run: go test -v ./...

        - name: Fly Deploy
          run: |
            if ! flyctl apps list | grep ${{ env.APP_NAME }}; then
              echo "No app found with the name ${{ env.APP_NAME }}, it will be created..."
              flyctl apps create --name ${{ env.APP_NAME }}
            fi
            flyctl deploy --remote-only
          env:
            FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
